### ISSUE TITLE
pyyaml and Pillow dependency

### ISSUE THREAD

**Issue by tschaume** [amueller/scipy-2016-sklearn#11]
FYI
1. `jupyter notebook` fails while loading nbextensions with `ImportError: No module named yaml`. Fixed by pip-installing `pyyaml`.
2. `python fetch_data.py` fails after downloading LFW data due to missing PIL library. Fixed by pip-installing `Pillow` (see https://github.com/Newmu/stylize/issues/1)

**Comment by rasbt** [comment]
Good call! Thanks for the note! I just updated the requirements and `check_env` code.
