### ISSUE TITLE
coordinate 7, 8, 9

### ISSUE THREAD

**Issue by amueller** [amueller/scipy-2016-sklearn#14]
They are currently weird. I'm not sure we should make this all about eigenfaces. I'd rather talk about more methods. But I'm not sure.

**Comment by rasbt** [comment]
yeah. I think we could use 
- a simpler dataset (maybe even Iris like in http://sebastianraschka.com/Articles/2015_pca_in_3_steps.html) to introduce dimensionality reduction (maybe only doing linear dim red in 7 to make it easy on people; based on my exp., people new to it find it challenging to understand that PCA will produce a new feature space). I suggest Iris in NB 7 before the section "Dimensionality Reduction for Visualization with PCA
  "  to explain transformation, the new feature space (eg 4D -> 2D), and the variance explained ratio in PCA
- 8 is a bit odd, I would maybe talk a bit more about scaling in the beginning; e.g., using the wine dataset. Then showing that standardization is important for logreg, svm, knn etc but not for dec. trees and rand. forests. After that, we could keep the facial recognition as a case study example in this notebook.
- 9 currently doesn't exist. Hm, I suggest that we use toy datasets for this exercise to explain what happens in manifold learning, e.g., separating the concentric circles, unrolling the swiss roll etc (http://sebastianraschka.com/Articles/2014_kernel_pca.html#examples-of-rbf-kernel-pca). What do you think?

**Comment by amueller** [comment]
I'm not a fan of the eigenfaces here, I think. I thought manifold learning was 26?

**Comment by amueller** [comment]
btw, SVD returns sorted eigenvectors, right? So you can remove that step ;)

**Comment by rasbt** [comment]
I think we can close that now!

> btw, SVD returns sorted eigenvectors, right? So you can remove that step ;)

you are right, but I didn't sort the "eigenvectors" from SVD I think :P
