### ISSUE TITLE
add links to notebooks in readme

### ISSUE THREAD

**Issue by amueller** [amueller/scipy-2016-sklearn#19]
we should do that after making sure the outline is as we want it.

**Comment by rasbt** [comment]
Okay I can do that after the renaming (I think you wanted to do the latter?)

**Comment by amueller** [comment]
I'll do that now

**Comment by amueller** [comment]
"want" is a strong word. btw do you have a good way of renaming stuff using git move?

**Comment by rasbt** [comment]
haha fair enough. Hm, I only have global rename scripts but nothing like this num-2 thing for notebook 7 or above :P. I think you don't even need to use git move, just the shell `mv`, it's equivalent

EDIT: 
I mean, the newer git versions will detect it automatically and rename files if you just use `mv`

**Comment by amueller** [comment]
no, mv loses the history, git mv does not.
