### ISSUE TITLE
Removing overfitting plots-checkpoint.ipynb

### ISSUE THREAD

**Issue by rasbt** [amueller/scipy-2016-sklearn#2]
The "overfitting plots-checkpoint.ipynb" file (aka add super messy notebook on overfitting to have it tracked and move i…") can now safely be removed, right!? :)

**Comment by amueller** [comment]
yeah totally.
Should we go on gitter for discussions?

Btw what did you mean by
- Unsupervised learning: Non-linear regression analysis ?

If you have time, i think it would be nice if we could submit our 
proposal in the next hour.

**Comment by rasbt** [comment]
Okay np, In this case, just disregard the email I just send you ;) Let's go to gitter then and discuss it further

**Comment by rasbt** [comment]
Closing this since it's been addressed in #3
