### ISSUE TITLE
move feature selection up?

### ISSUE THREAD

**Issue by amueller** [amueller/scipy-2016-sklearn#22]
Currently feature selection is after a bunch of unsupervised learning. I think it should be together with the supervised learning.

**Comment by rasbt** [comment]
Haha, sorry for all my counter-arguments in the last 5 minutes ... :P. I actually think that having a separate feature selection notebook may be useful rather ... for clarity and also as a future reference for the attendees. E.g., "How do I do feature selection again, ahja wait, we had this notebook here ... "

**Comment by amueller** [comment]
I didn't mean remove the notebook. I meant reorganize the toc. I think it would make more sense after 24 rather than after 26

**Comment by rasbt** [comment]
Oh okay, with that I agree! :) I thought you meant merging the content of the notebook into the other one ... Okay, then let me merge your pull requests first ...

**Comment by amueller** [comment]
done in 2d83abbeaf89a9540540ef71e2ecf6bef5adb982
