### ISSUE TITLE
make sure we have sensible exercises everywhere

### ISSUE THREAD

**Issue by amueller** [amueller/scipy-2016-sklearn#26]

**Comment by rasbt** [comment]
I will go through the notebooks after renaming, check, and open separate issues for where exercises are missing. Will do the same for the solutions. Let's then use the "Assignees" option here then and self-assign stuff to make sure we don't work on it simultaneous & redundantly

**Comment by amueller** [comment]
sounds good. I'll go to bed after the renaming though.

**Comment by rasbt** [comment]
no problem. Should do that too actually, but yeah, it's still too early for me I guess, doesn't work  if you are not used to it :P
