### ISSUE TITLE
Add exercises and solutions to 14 Model Complexity and GridSearchCV

### ISSUE THREAD

**Issue by rasbt** [amueller/scipy-2016-sklearn#47]

**Comment by rasbt** [comment]
oh I see you just started working on it. In case you are still brainstorming: I was just thinking about adding an exercise using learning curves: I.e., setup a "complex" model and ask sth along the lines "using this classifier and the learning curve function, see how the training/validation performance changes with respect to the training data; what can we conclude from that?"

**Comment by amueller** [comment]
That's a cool exercise, but I think we should keep it more simple. We want them to be able to solve it in about 10 minutes after seeing grid-search and model complexity for the first time. We can also add a learning curve exercise, but I was going to do just "run grid search on this model"

**Comment by rasbt** [comment]
Fair enough; I think we have a lot of ground to cover already anyway :). Reminds me of writing the book regarding page limits: so many more things to talk about but only so little time (to teach & prepare) ;)

**Comment by amueller** [comment]
you had a page limit? huh

**Comment by rasbt** [comment]
Haha, off topic: Yeah, initially 200 hundred. Was complaining soooo much though until I got 400 ;)
