### ISSUE TITLE
!!! No titanic data

### ISSUE THREAD

**Issue by rasbt** [amueller/scipy-2016-sklearn#62]
The titanic dataset seems to be missing (notebook 10). Do you have it on your local drive? It's probably pretty small so we could just add it to the repo instead of fetching it online.

**Comment by amueller** [comment]
I'm adding this. but I think we should use pandas to read it.

**Comment by rasbt** [comment]
Okay thanks! I am okay with pandas, but before adding another dependency, numpy's loadtxt or genfromtxt would have issues?

**Comment by amueller** [comment]
yeah they don't work on python3 basically ^^

**Comment by amueller** [comment]
ok I really don't understand the titanic notebook right now. I thought it would deal with missing values and categorical variables but it does not. wtf?

**Comment by rasbt** [comment]
Okay then! :). I think they would also have issues with the mixed types to some extend. pandas would be easier I agree

**Comment by rasbt** [comment]
Hm, I can't remember if there was a section on these things ...

**Comment by amueller** [comment]
there is not
