### ISSUE TITLE
No SMS data

### ISSUE THREAD

**Issue by rasbt** [amueller/scipy-2016-sklearn#63]
I also can't find the SMS dataset in the repo or fetch_data.py :(

**Comment by amueller** [comment]
at some point I asked "are you sure the fetch_data.py fetches the right datasets" ;)

**Comment by amueller** [comment]
https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection Should I work on that?

**Comment by rasbt** [comment]
Sorry, I think that was before we used SMS ... I am not sure ... 

but I am pretty sure that I was able to run all notebooks at some point. Maybe it was there as CSV, and I remember that we added the dataset directory to .gitignore (I typically use a different machine when I am at home so I think I still had it there as a leftover, sry :()

**Comment by rasbt** [comment]
yeah the dataset above looks good

**Comment by amueller** [comment]
hm... but adding it to the gitignore shouldn't change it if it was already  checked in? hm. maybe it was there..

**Comment by amueller** [comment]
yeah both titanic and smsspam were in the dataset folder

**Comment by rasbt** [comment]
I am curious what happened to them (and when), hmmm...

**Comment by amueller** [comment]
It's 466k, I'll add it.

**Comment by amueller** [comment]
in the old repo the datasets was already in gitignore. if I moved everything over, and not force added it, they are gone. Should have added a new remote and pushed to it. or maybe  I did that? I don't remember. But I'll fix it now.

**Comment by rasbt** [comment]
let me check my backups

**Comment by rasbt** [comment]
Just found them ... :) Shall I add titanic or are you already working on that?

![screen shot 2016-07-11 at 7 58 08 pm](https://cloud.githubusercontent.com/assets/5618407/16751820/f5eecd40-47a1-11e6-8034-f9b00868d5ea.png)

**Comment by amueller** [comment]
I added both in PRs
